{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}                         # shopverse-config
  # namespace: {{ .Values.namespace }}                       # shopverse-dev
  {{- with .Values.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
