apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}                         # shopverse-config
  namespace: {{ .Values.namespace }}                         # shopverse-dev
  labels:
    app: shopverse
data:
  DB_HOST: {{ .Values.mysql.DB_HOST | quote }}   # "shopverse-mysql-ens"
  DB_PORT: {{ .Values.mysql.DB_PORT | quote }}                  # "3306"
  DB_NAME: {{ .Values.mysql.DB_DATABASE | quote }}              # "shopverse"
  FRONTEND_ORIGIN: "*"                                       # "http://frontend-svc:8080"
