apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
      annotations:
        checksum/config: {{ include "user.config" . | sha256sum }}
    spec:
      containers:
        - name: user
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: global-config
