apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx # user
  labels:
    app: nginx # user
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx # user
  template:
    metadata:
      labels:
        app: nginx # user
      annotations:
        checksum/config: {{ include "user.config" . | sha256sum }}
    spec:
      containers:
        - name: nginx  # user
          image: nginx # "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: global-config
