apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}   # {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    {{- with .Values.labels }}
    matchLabels:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.labels }}
      labels:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        # ✅ LOCAL CONFIG checksum (only if exists)
        {{- with .Values.configmaps.envFrom.local }}
        {{- range . }}
        checksum/config-{{ . }}: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        {{- end }}
        {{- end }}

        # ✅ LOCAL SECRET checksum (only if exists)
        {{- with .Values.secrets.envFrom.local }}
        {{- range . }}
        checksum/secret-{{ . }}: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
        {{- end }}
        {{- end }}

        # ✅ GLOBAL CONFIG reloader (only if exists)
        {{- with .Values.configmaps.envFrom.global }}
        reloader.stakater.com/match: "{{ join "," . }}"
        {{- end }}

        # ✅ GLOBAL SECRET reloader (only if exists)
        {{- with .Values.secrets.envFrom.global }}
        reloader.stakater.com/match: "{{ join "," . }}"
        {{- end }}
        
    spec:
      # imagePullSecrets:
      # serviceAccountName: {{ include "pharma-service.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Values.containerName }}  # backend
          image: "{{ include "shopverse.backend.image" . }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}   # Always # IfNotPresent (default)
          ports:
            - containerPort: {{ .Values.service.targetPort }} # 8080
              protocol: TCP
              
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          envFrom:
            # =========================
            # CONFIGMAPS
            # =========================
            # ✅ LOCAL CONFIGMAPS
            # {{- with .Values.configmaps.envFrom.local }}
            {{- with .Values.configmaps.envFrom.local | default list }}
            {{- range . }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}

            # ✅ GLOBAL CONFIGMAPS
            {{- with .Values.configmaps.envFrom.local | default list }}
            {{- range . }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}

            # =========================
            # SECRETS
            # =========================
            # ✅ LOCAL SECRETS
            # {{- with .Values.secrets.envFrom.local }}
            {{- with .Values.secrets.envFrom.local | default list }}
            {{- range . }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}

            # ✅ GLOBAL SECRETS
            {{- with .Values.secrets.envFrom.global } default list }}
            {{- range . }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
                
          {{- with .Values.resources }}      
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.probes.startupProbe }}
          startupProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.probes.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.probes.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
