apiVersion: v2
name: shopverse
description: Common Helm chart for Shopverse microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - shopverse
  - microservice
  - go
maintainers:
  - name: Shopverse DevOps Team
    email: devops@shopverse.com
