apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  labels:
    app: platform
data:
  DB_HOST: "{{ .Values.global.db.mysql.host }}"
  DB_PORT: "{{ .Values.global.db.mysql.port }}"
  DB_NAME: "{{ .VAlues.global.db.mysql.database }}"
  APP_ENV: "{{ .Values.global.app.env }}"
