apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: shopverse-applicationset
  namespace: argocd

spec:
  generators:

    # =========================================
    # 🌍 PLATFORM (STATIC - FIRST)
    # =========================================
    - list:
        elements:
          - name: platform
            path: platform/global-config
            namespace: shopverse-dev
            wave: "-1"

    # =========================================
    # 🚀 SERVICES (AUTO DISCOVERY)
    # =========================================
    # Scans files, not directories
    # Only picks folders that contain Chart.yaml
    - git:
      repoURL: https://github.com/vaheedgit26/vg-travelbooking.git
      revision: HEAD
      files:
        - path: apps/*/Chart.yaml

    # {{path}}          → apps/backend/Chart.yaml
    # {{path.dirname}}  → apps/backend   ✅ IMPORTANT
    # {{path.basename}} → Chart.yaml

    # - git:
    #     repoURL: https://github.com/vaheedgit26/vg-travelbooking.git
    #     revision: HEAD
    #     directories:
    #       - path: apps/*

  # =========================================
  # 🎯 SINGLE TEMPLATE (USED BY BOTH)
  # =========================================
  template:
    metadata:
      name: "{{name | default path.dirname}}"     # '{{name | default path.basename}}'
      namespace: argocd
      annotations:
        # Platform uses its wave, services default to 0
        argocd.argoproj.io/sync-wave: '{{wave | default "0"}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/vaheedgit26/shopverse.git
        targetRevision: HEAD
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace | default "shopverse-dev"}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
