apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
spec:
  generators:
    - git:
        repoURL: https://github.com/YOUR_ORG/YOUR_REPO
        revision: HEAD

        directories:
          - path: charts/*   # 👈 THIS IS THE MAGIC
          #- path: charts/platform
          #  exclude: charts/platform/tests

  template:
    metadata:
      name: '{{path.basename}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/YOUR_ORG/YOUR_REPO
        targetRevision: HEAD
        path: '{{path}}'

        helm:
          valueFiles:
            - ../../environments/dev/values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
