namespace: shopverse-dev
# ──────────────────────────────────────
# BACKEND
# ──────────────────────────────────────
image:
  uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
  name: shopverse-backend
  version: v1
  
containerName: backend
imagePullPolicy: Always
terminationGracePeriodSeconds: 30

labels: 
  app: shopverse
  component: backend
  env: dev

deployment:
  name: backend-deploy
  replicas: 1
    
service:
  name: backend-svc
  type: ClusterIP
  port: 8080
  targetPort: 8080

configmap:
  name: configmap-backend
  data:
    DB_HOST: ""
    DB_PORT: "3306"
    DB_NAME: "shopverse"
    FRONTEND_ORIGIN: "*"

configmaps:
  local:
    - name: configmap-backend   
      fileName: configmap-backend.yaml
  global:
    - name: configmap-global    
      
secrets:
  local:
    - name: secret-backend      
      fileName: secret-backend.yaml
  global:
    - secret-global      

podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  requests: 
    cpu: "100m"
    memory: "128Mi" 
  limits:
    cpu: "200m"
    memory: "256Mi"

probes:
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
        
  readinessProbe:
    httpGet:
    path: /health
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    
autoscaling:
  enabled: false
  name: backend-hpa
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
