namespace: shopverse-dev
#--------------- Container --------------------------#
image:
  uri: 254405569649.dkr.ecr.us-east-1.amazonaws.com
  name: shopverse-backend
  version: v1

containerName: backend
imagePullPolicy: Always
terminationGracePeriodSeconds: 30
#--------------- Labels -----------------------------#
labels:
  app.kubernetes.io/name: shopverse
  app.kubernetes.io/component: backend
  app.kubernetes.io/env: dev
  app.kubernetes.io/version: 1.0.0
#--------------- Deployment -------------------------#
deployment:
  name: backend-deploy
  replicas: 1
#--------------- Service ----------------------------#   
service:
  name: backend-svc
  type: ClusterIP
  port: 8080
  targetPort: 8080
#--------------- Pod Annotations --------------------#
annotations:
  enabled: true
  values:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    # reloader.stakater.com/auto: "true"
#--------------- Security Context -------------------#
podSecurityContext:
  enabled: true
  values:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000

containerSecurityContext:
  enabled: true
  values:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
#--------------- Configmaps & Secrets ---------------#
configmap:
  enabled: true
  name: configmap-backend
  values:
    DB_HOST: ""
    DB_PORT: "3306"
    DB_NAME: "shopverse"
    FRONTEND_ORIGIN: "*"
	
secret:
  name: db-credentials
  create: false
	
envFrom:
  enabled: true
  values:
    - configMapRef:
        name: configmap-backend
    - secretRef:
        name: db-credentials    # Creates through ESO   
#--------------- Limits & Requests ------------------#
resources:
  enabled: true
  values:
    requests: 
      cpu: "100m"
      memory: "128Mi" 
    limits:
      cpu: "200m"
      memory: "256Mi"
#--------------- Healthcheck Probes ----------------# 
startupProbe:
  enabled: true
  values:
    httpGet:
      path: /health
      port: 8080
    failureThreshold: 10
    periodSeconds: 10
  
readinessProbe:
  enabled: true
  values:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
	
livenessProbe:
  enabled: true
  values:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 30
#--------------- Autoscaling -----------------------# 
autoscaling:
  enabled: false
  values:
    name: backend-hpa
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
#--------------- Service Account -------------------# 
serviceAccount:
  create: false
  values:
    name: backend-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/backend-role
