namespace: default
image: {}
deployment: {}
service: {}
labels: {}

imagePullPolicy: IfNotPresent

configmap:
  name: ""
  
secret:
  name: ""
  
imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}

resources: {}
probes:
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}

