namespace: default
image: {}
deployment: {}
service: {}
labels: {}

imagePullPolicy: IfNotPresent
terminationGracePeriodSeconds: 30

configmap: {}
configmaps: {}
secrets: {}
env: []
envFrom: []
  
imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
containerSecurityContext: {}

resources: {}

probes:
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}

autoscaling: {}
